kind: Service
apiVersion: v1
metadata:
  name: jbreak-coffee
  namespace: production
spec:
  selector:
    app: jbreak-coffee
  ports:
    - port: 8080
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: jbreak-coffee
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jbreak-coffee
    spec:
      containers:
      - name: jbreak-coffee
        image: docker.sebastian-daschner.com/jbreak-coffee:1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /jbreak-coffee/resources/
            port: 8080
      restartPolicy: Always
      imagePullSecrets:
      - name: regsecret
