kind: Service
apiVersion: v1
metadata:
  name: jbreak-coffee
spec:
  selector:
    app: jbreak-coffee
  ports:
    - port: 8080
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: jbreak-coffee
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jbreak-coffee
    spec:
      containers:
      - name: jbreak-coffee
        image: docker.sebastian-daschner.com/jbreak-coffee:1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /jbreak-coffee/resources/
            port: 8080
      restartPolicy: Always
      imagePullSecrets:
      - name: regsecret
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: jbreak-coffee
spec:
  rules:
    - host: coffee-shop.kubernetes.local
      http:
        paths:
        - path: /
          backend:
            serviceName: jbreak-coffee
            servicePort: 8080
---
